# Generated by Django 2.2 on 2021-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cèdula'),
        ),
    ]
