# Generated by Django 2.2 on 2021-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210823_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cédula'),
        ),
    ]
