# Generated by Django 2.2 on 2021-03-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ruc del distribuidor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Category', verbose_name='Categorìa'),
        ),
        migrations.AlterField(
            model_name='salelocation',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Direcciòn del local'),
        ),
    ]
