# Generated by Django 2.2 on 2021-04-08 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20210305_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='tax',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Category', verbose_name='Categorìa'),
        ),
    ]
