# Generated by Django 2.2 on 2021-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20210408_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dealer',
        ),
        migrations.AlterField(
            model_name='business',
            name='facebook',
            field=models.URLField(max_length=250, verbose_name='Dirección de facebook'),
        ),
        migrations.AlterField(
            model_name='business',
            name='whatsapp',
            field=models.URLField(max_length=250, verbose_name='Dirección de whatsapp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Category', verbose_name='Categorìa'),
        ),
    ]
