# Generated by Django 2.2 on 2021-08-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_auto_20210823_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='salelocation',
            name='direction',
            field=models.CharField(max_length=50, verbose_name='Dirección del local'),
        ),
    ]
