# Generated by Django 2.2 on 2021-08-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_auto_20210825_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='first_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.Category', verbose_name='Categoría'),
        ),
    ]
