# Generated by Django 2.2 on 2021-09-04 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20210903_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Guide'),
        ),
        migrations.AlterField(
            model_name='detguide',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='sale_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SaleLocation'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Dealer', verbose_name='Distribuidor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SaleLocation', verbose_name='Local de ventas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.SaleLocation'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salelocation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Business', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
