# Generated by Django 2.2 on 2021-09-08 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20210905_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_discount',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono celular o convencional'),
        ),
        migrations.AddField(
            model_name='client',
            name='score',
            field=models.IntegerField(blank=True, default=500, null=True, verbose_name='Puntaje'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='detsale',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría'),
        ),
    ]
